# Generated by Django 3.0.4 on 2020-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=255)),
                ('TotalCases', models.CharField(max_length=255)),
                ('NewCases', models.CharField(max_length=255)),
                ('TotalDeaths', models.CharField(max_length=255)),
                ('NewDeaths', models.CharField(max_length=255)),
                ('TotalRecovered', models.CharField(max_length=255)),
                ('ActiveCases', models.CharField(max_length=255)),
                ('Serious', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='India',
        ),
    ]
